// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJClVH-jQu-LKcmfYWTGtMDhcT7xv5kHk',
    appId: '1:1053326070004:web:0b70414a4eae2fd08b0ea1',
    messagingSenderId: '1053326070004',
    projectId: 'flutter-test-f9339',
    authDomain: 'flutter-test-f9339.firebaseapp.com',
    storageBucket: 'flutter-test-f9339.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDU0BB-1mlwpxtGCyAe4SrkMoGrINGRZo',
    appId: '1:1053326070004:android:51a67457853fb56b8b0ea1',
    messagingSenderId: '1053326070004',
    projectId: 'flutter-test-f9339',
    storageBucket: 'flutter-test-f9339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsKzrLGsLHPYmmsXuRpnms24ft3gGE8KA',
    appId: '1:1053326070004:ios:3c584f3730ff42ee8b0ea1',
    messagingSenderId: '1053326070004',
    projectId: 'flutter-test-f9339',
    storageBucket: 'flutter-test-f9339.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsKzrLGsLHPYmmsXuRpnms24ft3gGE8KA',
    appId: '1:1053326070004:ios:3c584f3730ff42ee8b0ea1',
    messagingSenderId: '1053326070004',
    projectId: 'flutter-test-f9339',
    storageBucket: 'flutter-test-f9339.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
